MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  WEIGHTS: "./pvt_v2_b2_li_C4.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 1
    NAME: "build_PVT_backbone"
    TYPE: "pvt_v2_b2_li"
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "PVTROIHeads"
DATASETS:
  TRAIN: ("visdrone_train_nonvoc",)
  TEST: ("visdrone_val",) 
  # ("visdrone_val",)("visdrone-train-half-bd-traffic",)("visdrone-train-half-bd-traffic",)("visdrone-train-half-bd-traffic",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002
  STEPS: (750, 1000) #(85000, 100000)
  MAX_ITER: 180000 #110000
  CHECKPOINT_PERIOD: 1000 #110000
INPUT:
  MIN_SIZE_TRAIN: (100, 400) # (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: "./output/fsod/single_branch_pretraining_vbtv_pvt_v2_b2_li/"
TEST:
  EVAL_PERIOD: 10000
VERSION: 2


# MIN_SIZE_TRAIN: (100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)
# MAX_SIZE_TRAIN: 200
# MIN_SIZE_TEST: 600
# MAX_SIZE_TEST: 1000
# MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
# MAX_SIZE_TRAIN: 1333
# MIN_SIZE_TEST: 800
# MAX_SIZE_TEST: 1333
#(750, 999)

# STEPS: (2500, 3000)
#   MAX_ITER: 3100
#   CHECKPOINT_PERIOD: 3100
# INPUT:
#   MIN_SIZE_TRAIN: (100, 800)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1333
# OUTPUT_DIR: "./output/fsod/single_branch_pretraining_vbtv_pvt_v2_b2_li/"
# TEST:
#   EVAL_PERIOD: 1000
# VERSION: 2
