_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  WEIGHTS: "./output/fsod/single_branch_pretraining_pascalvoc_split1_pvt_v2_b2_li/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 1
    NAME: "build_FCT_backbone"
    TYPE: "pvt_v2_b2_li"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
OUTPUT_DIR: './output/fsod/two_branch_training_pascalvoc_split1_pvt_v2_b2_li'
DATASETS:
  TRAIN: ("voc_2007_trainval_base1", "voc_2012_trainval_base1")
  TEST: ("voc_2007_test_all1",)
  TEST_KEEPCLASSES: 'all1'
  TEST_SHOTS: (1,2,3,5,10)
INPUT:
  FS:
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 10
  MIN_SIZE_TRAIN: (100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)
  MAX_SIZE_TRAIN: 200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00002
  STEPS: (150, 199)  
  MAX_ITER: 250 #10000
  WARMUP_ITERS: 50
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 1000
  HEAD_LR_FACTOR: 2.0
TEST:
  EVAL_PERIOD: 1000
#STEPS: (750, 999)  
#MAX_ITER: 5000 #10000